services:
  app:
    image: iantdocker/qualymentos_app:latest
    container_name: qualymentos_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/qualymentos
      SPRING_DATASOURCE_USERNAME: postgres 
      SPRING_DATASOURCE_PASSWORD: 1234
      restart: always   # reinicia automaticamente se cair

  db:
    image: iantdocker/qualymentos_db:latest   # ou 'postgres:17' se preferir usar direto
    container_name: qualymentos_db
    environment:
      POSTGRES_DB: qualymentos
      POSTGRES_USER: postgres             
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: