spring.application.name=Qualymentos
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://10.211.0.31:5430/db_01

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.docker.compose.enabled=false

